docs(rh-dialog): update docs
RedHat-UX/red-hat-design-system pull request #1001
Opened 2023-05-24 20:09 UTC by eyevana

Closes #927

## What I did

1. Updated the documentation for the dialog element according to the specs outlined in #927.

## Testing Instructions

1. Review latest docs at https://deploy-preview-1001--red-hat-design-system.netlify.app/elements/dialog and verify they match the design specs as well as the docs cleanup guide https://github.com/RedHat-UX/red-hat-design-system/wiki/Docs-Cleanup-Q2-2023-Checklist#code-page.

2023-05-28 10:30 UTC, bennypowers requested changes

2023-05-28 10:30 UTC, bennypowers commented on elements/rh-dialog/docs/dialog-16px-spacer.png
do we need to copy these for each element? can't we just keep one copy for everyone?

2023-05-30 15:04 UTC, eyevana commented on elements/rh-dialog/docs/dialog-16px-spacer.png
Yep, that makes sense. Where's the best spot to store these shared SVGs? `docs/assets/spacing`? Is it cool if  break this out into a post-clean up task and update/verify all elements are referring to the shared spacers?

2023-05-30 15:16 UTC, bennypowers commented on elements/rh-dialog/docs/dialog-16px-spacer.png
yeah let's do that

2023-05-30 15:17 UTC, bennypowers approved these changes

2023-05-30 15:25 UTC, eyevana commented on elements/rh-dialog/docs/dialog-16px-spacer.png
https://github.com/RedHat-UX/red-hat-design-system/issues/1005

2023-05-30 15:25 UTC, merged