docs: header permalinks
RedHat-UX/red-hat-design-system pull request #1051
Opened 2023-06-08 09:12 UTC by bennypowers

Fixes #119

## What I did

1. add header-link style permalinks to markdown

## Notes to Reviewers

The approach taken in this PR differs from the original design in #119, for accessibility reasons, so please take a look @coreyvickery 

This initial draft does not style the header links any differently from regular links, but that's up for revision, naturally.

This PR relies on a patch to pfe-tools. If the approach taken here is desirable, please wait on merging this until we upstream the changes (cc @eyevana as this may affect cpelements docs site)

2023-06-11 07:52 UTC, bennypowers commented
Greg's best-of-all-worlds demo

https://codepen.io/hellogreg/pen/NWEPppE

2023-06-13 09:51 UTC, bennypowers commented on patches/@patternfly+pfe-tools+1.3.0.patch
leaving this comment to make sure we don't merge before pfe tools is updated

2023-06-13 09:52 UTC, bennypowers commented
@hellogreg PTAL, I made the copy element wrap the headings.

2023-06-16 14:21 UTC, zeroedin requested changes
When you scroll the page and then click the copy-permalink button the alert that pops up is underneath the `back-to-top` button.  We should apply a z-index to these alerts so they pop over that button as they can be dismissed and the `back-to-top` button can not.

![image](https://github.com/RedHat-UX/red-hat-design-system/assets/13666/52d3c795-b0e0-48b8-9db4-5fc01321cd57)

2023-06-16 15:28 UTC, zeroedin approved these changes

2023-06-16 15:28 UTC, merged