docs: added jspm and redhatstatic cdn examples
RedHat-UX/red-hat-design-system pull request #1147
Opened 2023-07-17 12:46 UTC by heyMP

This is a draft PR to support an upcoming developer experience demo.  We want to show how you can leverage the CDN / Importmap options when using our library.

Something like this: https://stackblitz.com/edit/web-platform-r96bye?file=index.html

## What I did

1. Added jspm.dev and redhatstatic cdn examples to the code tab of the elements pages.

Needs some prose cleanup and maybe reorganizing.

2023-07-24 12:43 UTC, bennypowers commented on docs/_plugins/shortcodes/renderInstallation.cjs
> +Red Hat CDN (recommend)
```suggestion
Red Hat CDN (recommended)
```

2023-07-24 12:43 UTC, bennypowers commented on docs/_plugins/shortcodes/renderInstallation.cjs
> +Red Hat CDN (recommend)
since CDN is recommended, let's put it before the `npm i` snippet

2023-07-24 12:43 UTC, bennypowers commented on docs/_plugins/shortcodes/renderInstallation.cjs
> +  import '@rhds/elements/rh-cta/rh-cta.js';
```suggestion
  import '@rhds/elements/${docsPage.tagName}/${docsPage.tagName}.js';
```

2023-07-24 14:14 UTC, bennypowers commented on docs/_plugins/shortcodes/renderInstallation.cjs
it would be nice to put the different snippets in rh-tabs, and sync the selection via localStorage

2023-09-26 08:51 UTC, bennypowers commented on docs/_plugins/shortcodes/renderInstallation.cjs
took a whack at this. LMK what you think

cc @coreyvickery @marionnegp @nikkimk

2023-10-02 14:24 UTC, marionnegp commented on docs/_plugins/shortcodes/renderInstallation.cjs
@bennypowers, I checked a couple elements pages, but I don't see your changes in the Code tabs. Am I looking at the wrong thing?

2023-10-03 21:04 UTC, bennypowers commented
@marionnegp confirmed. The change I made is not visible in code tabs

I will take a closer look after my holiday

2023-10-08 15:01 UTC, bennypowers commented on docs/_plugins/shortcodes/renderInstallation.cjs
@brianferry 's fix from #1118 was applied to this pr

2023-11-27 15:22 UTC, markcaron requested changes
Make the installation tabs `vertical` and `box` variant.

2023-11-27 16:02 UTC, markcaron approved these changes
Little Grogu, The Mandalorian

2023-11-27 16:04 UTC, merged