docs: updated component max character / max word counts
RedHat-UX/red-hat-design-system pull request #1184
Opened 2023-08-02 14:45 UTC by nikkimk

## What I did

Worked with @coreyvickery to determine which components/parts of components should max character counts in the guidelines pages of docs, and added to or updated docs accordingly:

- [x] Accordion (title was updated, panel doesn't need a max count)
- [x] Alert (already exists)
- [x] Announcement
- [x] Audio player (already exists for title and description, not needed elsewhere)
- [x] Avatar (does not need max count)
- [x] Badge (already exists)
- [x] Blockquote (does not need max count)
- [x] Button (already exists)
- [x] Call to action (already exists)
- [x] Card (does not need max count)
- [x] Code block (does not need max count)
- [x] Dialog (already exists)
- [x] Disclosure
- [x] Footer (does not need max count)
- [x] Jump links
- [x] Navigation, primary
- [x] Navigation, secondary (already exists)
- [x] Link(s)
- [x] Pagination (does not need max count)
- [x] Popover (already exists)
- [x] Progress steps
- [x] Promo
- [x] Spinner (already exists)
- [x] Statistic (already exists)
- [x] Sticky banner
- [x] Sticky card
- [x] Subnav  (already exists)
- [x] Tabs (already exists)
- [x] Tag (already exists)
- [x] Tile
- [x] Tooltip 

## Testing Instructions

1. From the DP, verify that each guidelines page has max character / word counts, if applicable.

## Notes to Reviewers

- This is a work in progress.
- We determined that some components or parts of components did not require a max count.

2023-09-21 14:29 UTC, nikkimk commented
@bennypowers there should be text preceding all of the tables. Some of it existed before this PR. PTAL

2023-10-11 07:21 UTC, bennypowers approved these changes

2023-11-13 19:32 UTC, marionnegp requested changes
Instead of "The maximum character count for the elements of a [insert element/pattern] are listed below", can we say, "The recommended maximum character count for the elements of a [insert element/pattern] are listed below and include spaces"?

2023-11-13 21:22 UTC, nikkimk commented
@marionnegp ptal

2023-11-14 03:19 UTC, marionnegp requested changes
Changes are looking good!

- [ ] Didn't notice this last time, but on Audio Player's page, the first column header is "Tab count." Is that right?
- [ ] Do you think it's valuable to add a sentence about how the character count includes spaces? I was thinking it could be a caption under the tables.

2023-11-14 20:18 UTC, marionnegp approved these changes
Local Grandma Tramples Musician

2023-11-27 15:27 UTC, merged