feat(navigation-secondary): add roving tabindex controller
RedHat-UX/red-hat-design-system pull request #1225
Opened 2023-09-18 16:29 UTC by zeroedin

## What I did

1. Add roving tabindex controller to navigation-secondary top level nav slotted links.

- [x] Add changeset

## Testing Instructions

1. View Deploy preview

## Notes to Reviewers

2023-09-21 15:54 UTC, bennypowers reviewed
L...pretty?GTM

2023-09-21 15:54 UTC, bennypowers commented on elements/rh-navigation-secondary/rh-navigation-secondary.ts
> +      this.#tabindex.initItems(this.#navItems);
```suggestion
    this.#tabindex.initItems(this.#navItems ?? []);
```

six of one... 
this comment is purely aesthetic, feel free to pass over it

2023-09-25 14:27 UTC, zeroedin commented on elements/rh-navigation-secondary/rh-navigation-secondary.ts
> +  @queryAssignedElements({ slot: 'nav' }) private _nav?: HTMLElement[];
yeah the native decorators will be nice to no longer have to do this for private decorated fields

2023-09-26 15:28 UTC, bennypowers approved these changes
Code looks good to me. @nikkimk would you please apply your usability expertise here?

2023-09-26 15:32 UTC, brianferry requested changes
Questions about RTI functionality - blocker

2023-09-28 18:52 UTC, zeroedin commented
> Questions about RTI functionality - blocker

from @nikkimk in chat:
esc -> closes and sets focus on the last active tab
tab -> closes and sets focus on the next tab
shift+tab -> closes and sets focus on previous tab

2023-10-10 14:55 UTC, brianferry approved these changes
Keyboard navigation in the demo looks good to me, great job!

2023-10-16 13:47 UTC, nikkimk approved these changes
lgtm

2023-10-16 13:54 UTC, merged