fix(cta): revert removal of ccolorContextProvider, deprecate instead
RedHat-UX/red-hat-design-system pull request #1245
Opened 2023-10-02 16:02 UTC by zeroedin

## What I did

1. Revert removal of colorContextProvider, deprecate instead

### TODO:

- [ ] Figure out language for how we want to mark up the changeset for this reversal.

## Testing Instructions

1.

## Notes to Reviewers

2023-10-10 16:58 UTC, bennypowers requested changes
this is fine. I suggest putting all new lines in one place (even though it would not follow ordering guidelines) so that you can wrap those lines in `// START DEPRECATION WARNING` and `// END DEPRECATION WARNING` comments

This will also need an `@attr color-palette {@deprecated reason}` jsdoc on the class, and the pr (i.e. commit) title should be updated

2023-10-10 20:43 UTC, zeroedin commented
> This will also need an `@attr color-palette {@deprecated reason}` jsdoc on the class, and the pr (i.e. commit) title should be updated

Doesn't look like `cem` provides @deprecated on @attr like it does on @slot (see rh-footer). 

Maybe just a depreciated note in the description will suffice?

2023-10-15 05:42 UTC, bennypowers commented
> > This will also need an `@attr color-palette {@deprecated reason}` jsdoc on the class, and the pr (i.e. commit) title should be updated
> 
> Doesn't look like `cem` provides @deprecated on @attr like it does on @slot (see rh-footer).
> 
> Maybe just a deprecated note in the description will suffice?

we can manually update the cem in a post-build script then. keep the jsdoc tho

2023-10-15 05:44 UTC, bennypowers approved these changes

2023-10-15 05:44 UTC, bennypowers commented on elements/rh-cta/rh-cta.ts
> +
```suggestion
```

2023-10-15 05:44 UTC, bennypowers commented on elements/rh-cta/rh-cta.ts
> +   * @deprecated
```suggestion
   * @deprecated do not use the color-palette attribute, which was added by mistake. use context-providing containers (e.g. rh-card) instead
```

2023-10-16 05:20 UTC, merged