docs: element updates
RedHat-UX/red-hat-design-system pull request #1256
Opened 2023-10-10 17:27 UTC by eyevana

## What I did

Detailed list of changes in issue #1252.

1. Updated element screenshots
2. Created filter to transform titles to sentence case
3. Fixed all links on elements page; should be going to overview tab by default

Closes #1252

2023-10-10 21:22 UTC, coreyvickery commented
@eyevana I'm not seeing `Table` or is that addition in the other issue?

2023-10-10 21:30 UTC, coreyvickery commented
> @eyevana I'm not seeing `Table` or is that addition in the other issue?

Nevermind, it is in the other PR.

2023-10-10 21:31 UTC, coreyvickery commented
@eyevana

Tiny final changes:

- [ ] Change h1 to `All elements`
- [ ] Remove period in the `Avatar` description
- [ ] Remove period in the `Code block` description
- [ ] Change `Navigation (secondary)` description to `Propagates related content across a series of pages`

You can merge after these are done, I don't need to approve a second time.

2023-10-11 05:38 UTC, bennypowers requested changes

2023-10-11 05:38 UTC, bennypowers commented on elements/rh-avatar/rh-avatar.ts
patch changeset for fixing docs

2023-10-11 05:38 UTC, bennypowers commented on elements/rh-code-block/rh-code-block.ts
patch changeset for fixing docs

2023-10-12 08:02 UTC, bennypowers commented on .changeset/loud-dolphins-enjoy.md
> +Updated all elements docs page with new summaries, images, and correct links
as far as the changeset is concerned (i.e. the npm package), the docs pages are not important, rather, the changes to the custom-elements.json file are what are important here.
```suggestion
`<rh-avatar>`:
`<rh-code-block>`: Updated custom elements manifest summaries
```

2023-10-15 07:05 UTC, bennypowers approved these changes

2023-10-16 13:45 UTC, merged