docs(tabs): add base theme demo
RedHat-UX/red-hat-design-system pull request #1347
Opened 2023-11-15 21:20 UTC by zeroedin

## What I did

1. Adds base theme demo

Closes #1336 

## Testing Instructions

1.

## Notes to Reviewers

2023-11-21 10:35 UTC, bennypowers requested changes
it seems to me that the only thing `theme` changes is it toggles this css:

```css
:host([active][theme="base"]) #rhds-container {
  --_active-tab-border-color:
    var(
        --rh-tabs-active-border-color,
        var(--rh-color-border-interactive-on-light, #0066cc)
      );
}

:host([active][theme="base"]) #rhds-container.dark {
  --_active-tab-border-color:
    var(
        --rh-tabs-active-border-color,
        var(--rh-color-border-interactive-on-dark, #73bcf7)
      );
}
```

Wouldn't it be better to instruct users to set `--rh-tabs-active-border-color`, rather than using an attribute which is both

1. unique to tabs and to this specific use case, and 
2. at the same time squatting on terminology which is in use everywhere else in the design system

"Theme", as we've seen, is a loaded and amorphous concept, one we're working very hard to simplify and define for our user's benefit. Does it help our users to have multiple, subtly different, current-task-dependent definitions of the word `theme` in our DS?

I suggest we mark this attribute as deprecated and instead document how to use the component tokens to set custom colours.

2023-11-21 21:25 UTC, zeroedin commented
> "Theme", as we've seen, is a loaded and amorphous concept, one we're working very hard to simplify and define for our user's benefit. Does it help our users to have multiple, subtly different, current-task-dependent definitions of the word theme in our DS?
>
> I suggest we mark this attribute as deprecated and instead document how to use the component tokens to set custom colours.

@coreyvickery @marionnegp this also doesn't exist in the current `rh-tabs` figma file or UX dot, was this an intentional drop from [XD](https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/d626e1c7-1e33-4edd-b131-f5effbc91968/specs/) -> Figma transistion?  Maybe it's something worth depreciating and implementing as @bennypowers is suggesting.

2023-11-27 16:00 UTC, bennypowers requested changes

2023-11-27 16:19 UTC, zeroedin commented on elements/rh-tabs/rh-tabs.ts
>    @property({ reflect: true }) theme?: 'base' | null = null;
looks like the decorator is `@deprecation` also it wants an `alias` which looks like original intent is when a attribute changes from one to another.  In this case we are removing it for direct usage of the css property itself.

Is this acceptable use?
```
 @deprecation({ alias: 'css property --rh-tabs-active-border-color', reflect: true, attribute: 'theme' }) theme?: 'base' | null = null;
```
Generates following warning:
```
logger.ts:50 [rh-tabs#rh-tabs-w1wi2quqq] theme is deprecated, use css property --rh-tabs-active-border-color instead
```

2023-11-28 17:21 UTC, bennypowers approved these changes

2023-11-28 17:28 UTC, merged