docs: samples
RedHat-UX/red-hat-design-system pull request #1350
Opened 2023-11-16 13:51 UTC by bennypowers

## What I did

1. add `{% sample %}` paired shortcode
2. use it for:
    - card
    - timestamp
3. tinkered with codeblock's css so that it works nice in grids. did i break stuff? you tell me :laughing:

2023-11-16 14:00 UTC, bennypowers commented
I don't think this needs to be comprehensive. the only blockers on this should be things like:

- the design needs improvements
- something is broken

but, like .. "we should also do this for xyz element" can be a follow up pr

2023-11-28 16:11 UTC, brianferry commented on docs/_plugins/shortcodes/sample.cjs
> +      code = 'show',
Should this be a boolean?

2023-11-28 16:11 UTC, brianferry commented on elements/rh-accordion/docs/10-style.md
> +<script type="module">import '/assets/elements/uxdot-code-sample.js';</script>
Would it be possible to move this into the sample script?

2023-11-29 20:56 UTC, brianferry commented on elements/rh-accordion/docs/10-style.md
> +<script type="module">import '/assets/elements/uxdot-code-sample.js';</script>
Fair point, I had thought about #1 but like you said the browser should in theory be able to handle that but it doesn't really impact anything other than needing to remember to put that line on a page when the code sample import is being used.

2024-01-08 16:50 UTC, brianferry approved these changes
Went through the demo files and the docs and everything looks good to me

2024-01-08 18:29 UTC, zeroedin requested changes
These blocks should have a red border and icon like the top with the image

![image](https://github.com/RedHat-UX/red-hat-design-system/assets/13666/4158458b-0def-48f9-bfb8-db38f0214e64)


![image](https://github.com/RedHat-UX/red-hat-design-system/assets/13666/d3bd45f4-b7d7-4b2e-9e84-55be9d323712)

2024-01-08 18:33 UTC, zeroedin reviewed
General comment non blocker to this PR.  Is the intent to replace all "sample" images with real working components?  If so should we get those components not in this PR added to the backlog to follow up on. /cc @markcaron

2024-01-08 18:50 UTC, zeroedin requested changes
https://deploy-preview-1350--red-hat-design-system.netlify.app/elements/accordion/style/#theme

Color Palette isn't clickable here in Chrome 120.0.6099.199:

![image](https://github.com/RedHat-UX/red-hat-design-system/assets/13666/a24bb190-048d-43d6-8e9a-c4c8a3f76832)

Doesn't display at all in Safari  17.2.1 :

![image](https://github.com/RedHat-UX/red-hat-design-system/assets/13666/234fcb32-8c57-45ee-b6d8-ee42292410fd)

And is weirdly cropped in Firefox 115.6.0esr (64-bit)

![Screenshot 2024-01-08 at 1 47 10 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/13666/8133bbdc-3384-477b-9804-768f79753503)

2024-01-09 16:08 UTC, markcaron commented
> General comment non blocker to this PR. Is the intent to replace all "sample" images with real working components? If so should we get those components not in this PR added to the backlog to follow up on. /cc @markcaron

@zeroedin not necessarily _all sample images_, but at least the ones that make the most sense.

2024-01-10 20:00 UTC, bennypowers commented
the anatomy sample component is at the MVP level. if that's the only blocker, slap a `hidden` attr on it and let's merge this puppy

2024-01-10 20:52 UTC, markcaron commented
@bennypowers honestly, I feel like the Sample Component has gone beyond the original intention.

Don't get me wrong, it's looking pretty cool with all the features, but I think it changes the context of the design sections, like the Style tab. We don't want to replace ALL images, since images still have their use in these sections.

For example, if you're wanting to see all the different Sizes of the Audio Player, it looks "fine" (aside from the last one breaking out of the container):

<img width="1197" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/c991089d-bd4c-4dbc-a8f4-1c4a2140806c">

But, on Mobile, you lose the visual since ALL of the Audio Player samples become "mobile friendly":

<img width="531" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/6861db04-7a0b-442f-b319-6d97c0263104">

We want the image to show ALL the sizes/options, and not have the visual representation / Sample Component react live to the browser or container width.

_Note: the little purple tooltips are also wonky on mobile, but that's a separate topic_

I feel like the true use of the Sample Component lives on the Code and Overview tabs, where we'd want to show a live example, and not on design sections where we'd want to highlight specific features (that retain their context across devices).

For example, on mobile, the Configuration section is using an image still, and it doesn't lose it's context—you can still see all the config options visually:

<img width="536" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/73e00f03-0792-4024-accb-9d75852d81b0">

Hopefully that makes sense.

This isn't a blocker anyway. Maybe we take this out of the Caterpie release, and fast follow with it since it's just docs.

2024-01-11 06:15 UTC, bennypowers commented
yup, makes sense to me

2024-01-26 14:35 UTC, zeroedin commented
Do we want to hold on `uxdot-anatomy-sample` until we have time to flesh it out more?  I think it would be nice to get the `uxdot-code-sample` component in without that anatomy holding this PR up.

2024-05-21 14:19 UTC, bennypowers commented
Superceeded mostly by #1465

2024-05-21 14:19 UTC, closed without merging