feat: change "primitive" to "crayon" or "crayon colors"
RedHat-UX/red-hat-design-system pull request #1357
Opened 2023-11-20 18:10 UTC by marionnegp

Updated the Color page

## Testing Instructions

1. View Color page in DP

2023-11-20 18:14 UTC, marionnegp commented
@coreyvickery, I made these updates based on the discussion in last week's standup to keep the term "crayon" over "primitives."

2023-11-21 12:47 UTC, bennypowers requested changes

2023-11-21 12:47 UTC, bennypowers commented on docs/foundations/color/index.md
> +Our design system includes multiple sets of colors known as <strong>"crayon" colors</strong>. Crayon colors reference hard-coded values, but offer no information about usage. <strong>Semantic</strong
```suggestion
Our design system includes multiple sets of colors known as **"crayon" colors**. Crayon colors reference hard-coded values, but offer no information about usage. **Semantic** colors reference crayon colors and define how a color is used. Semantic naming is essential not just for color, but for all foundational styles.
```

2023-11-22 23:33 UTC, coreyvickery approved these changes

2023-11-23 19:12 UTC, merged