fix(tabs)!: tab button font-size should be set to 16px
RedHat-UX/red-hat-design-system pull request #1362
Opened 2023-11-27 20:09 UTC by zeroedin

## What I did

1. Added `--rh-tabs-link-font-size` to with default font-size of 1rem

Reference #1361

### TODO:
- [ ] Determine if breaking change or not, I can see it either way.    

## Testing Instructions

1.

## Notes to Reviewers

2023-11-27 21:57 UTC, marionnegp approved these changes
Levitating Gnomes Travel Merrily

2023-11-28 14:50 UTC, brianferry approved these changes
LGTM Generators Trivialize Merges

2023-11-28 15:04 UTC, bennypowers requested changes
instead just set rh-tab's font size on rh-tabs, no opostrophe. if slotted specificity is a thing, then fix it in ux-dot

2023-11-28 15:29 UTC, bennypowers approved these changes

2023-11-28 15:47 UTC, merged