fix(table): custom background hover colors
RedHat-UX/red-hat-design-system pull request #1462
Opened 2024-01-25 22:16 UTC by zeroedin

## What I did

1.  Correctly implemented fallbacks for public api css props, added to cem docs, renamed and deprecated old var name.

Closes #1454 

## TODO

- [ ] Figure out how to properly document the @deprecate on the @cssprop?
- [ ] Add changeset

## Testing Instructions

1.

## Notes to Reviewers

2024-01-26 05:47 UTC, bennypowers requested changes

2024-01-26 05:47 UTC, bennypowers commented on docs/release-notes.md
looks like maybe you branched off of staging/chansey, can you rebase to main?

2024-01-26 13:56 UTC, zeroedin commented on docs/release-notes.md
Ok I think I resolved it, had to force push though FYI.

2024-01-26 13:59 UTC, bennypowers reviewed
Needs a changeset then we're g2g

2024-01-26 14:12 UTC, zeroedin commented
> Needs a changeset then we're g2g

I couldn't figure out a better way to document the deprecation then just adding the deprecation note to the description on the token in the jsdoc.  Is this something we could improve in the future customizing the format?

2024-01-29 14:07 UTC, bennypowers approved these changes

2024-01-29 14:07 UTC, merged