fix(tile): correct icon slot visibility
RedHat-UX/red-hat-design-system pull request #1504
Opened 2024-03-19 17:27 UTC by zeroedin

## What I did

1. Fixed template logic to correctly display slotted content when the icon attribute is undefined.

Closes #1503 

## Testing Instructions

1. View deploy preview icon demo

## Notes to Reviewers

2024-03-19 17:32 UTC, zeroedin commented on elements/rh-tile/rh-tile.ts
ooh good call

2024-03-19 18:31 UTC, bennypowers requested changes
Please inline the controller call to render

2024-03-19 18:31 UTC, bennypowers commented on elements/rh-tile/rh-tile.ts
> +    super.connectedCallback();
Just call this in render. No need for class private state

2024-03-21 06:20 UTC, bennypowers approved these changes
little graphics through markup

2024-03-21 06:21 UTC, merged