fix(rh-tile): css custom properties
RedHat-UX/red-hat-design-system pull request #1685
Opened 2024-07-01 14:43 UTC by markcaron

## What I did

1. Fixed `--rh-tile-border-color` custom prop (and all other public custom props) inheritance

## Testing Instructions

1. Go to Custom Props demo page
2. Test out overriding the different public [CSS custom properties listed](https://ux.redhat.com/elements/tile/code/#rh-tile) in the docs

Closes: #1680

2024-07-03 11:46 UTC, bennypowers commented
This should probably get some prose on the guidelines or code page about proper and improper use of the css props

2024-07-09 16:08 UTC, marionnegp requested changes
I was able to make some beautiful, very accessible tiles with those custom props.
![Screenshot 2024-07-09 at 12 05 53 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/3379817f-04a4-41df-a1fa-06dd4cde263b)

The two that didn't work for me were `--rh-tile-link-text-decoration` and `--rh-tile-link-color`. Without using custom props, the linked heading wasn't showing the correct styling either. It might be related to the issue from #1692.

2024-07-11 13:36 UTC, markcaron commented
@marionnegp, I found the bug with `--rh-tile-link-text-decoration`, but wasn't able to replicate any issues with `--rh-tile-link-color` (it worked fine for me). Maybe `--rh-tile-link-color` was fixed in #1692 ?

Screenshot showing the custom props working:

<img width="1036" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/32d5dcbc-ecad-4b85-9b75-b68a3edd8bed">

Do you mind retesting?

2024-07-11 13:50 UTC, marionnegp approved these changes

2024-07-11 15:08 UTC, merged