fix(accordion): heading tags
RedHat-UX/red-hat-design-system pull request #1715
Opened 2024-07-16 06:53 UTC by bennypowers

also improves perf

## What I did

1. remove most of the js in rh-accordion-header
2. remove the anonymous slot from rh-accordion-header
3. calculate the shadow header based on child content
4. handle incorrect values for `heading-tag` attr (e.g. `2` instead of `h2`)

## Testing Instructions

1. carefully read the unit tests, ensure that they accurately express user expectations

2024-07-22 20:08 UTC, markcaron commented
@bennypowers there are a few `<rh-accordion-header>` bugs that may or may not be related (perhaps indirectly) to some of the work you're doing here.

Can we tackle one or more of these?

1. #1637 
2. #1675 

And, then there's also #1609

2024-08-20 15:37 UTC, adamjohnson commented on elements/rh-accordion/rh-accordion-header.ts
>  import { property } from 'lit/decorators/property.js';
Side note: the line numbers referenced here and below are not relevant to the comments.

...Probably should have just added these three points as a comment. /shrug.

2024-08-20 15:39 UTC, bennypowers commented on elements/rh-accordion/rh-accordion-header.ts
>  import { property } from 'lit/decorators/property.js';
that was the idea, no?
if js fails, fall back to the heading elements,
if js loads, use the content of the headings but remove the element

are you saying we need to in that case add aria heading level to the heading elements afterwards?

2024-08-20 16:00 UTC, adamjohnson commented on elements/rh-accordion/rh-accordion-header.ts
>  import { property } from 'lit/decorators/property.js';
The appropriate approach would be:

```html
<h3>
  <button>Attributes omitted for brevity</button>
</h3>
```

Detecting which heading level to use based off of content from lightdom / users.

Or perhaps using [ARIA heading roles](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/heading_role).

Is it feasible to make the `#container` a heading element (or use ARIA heading roles there)?

2024-08-20 18:08 UTC, bennypowers commented on elements/rh-accordion/rh-accordion-header.ts
>  import { property } from 'lit/decorators/property.js';
If we apply aria level to the ElementInternals of the rh-accordion-header element, that ought to do i think

2024-08-20 18:11 UTC, adamjohnson commented on elements/rh-accordion/rh-accordion-header.ts
>  import { property } from 'lit/decorators/property.js';
Yes, and `role="heading"`.

2024-08-20 19:20 UTC, marionnegp requested changes
I'm still seeing the wrong text style in this branch's demos when I open them in a separate tab. The font size should be 18px (`--rh-font-size-body-text-lg`). Weight should be medium (`--rh-font-weight-body-text-medium`).

I'm also seeing a space below the heading text, which may be because the text isn't large enough to fill that space. Here's what spacing looks like with the caret icon using the updated Brand icon
![Screenshot 2024-08-20 at 3 19 02 PM](https://github.com/user-attachments/assets/9cd66cdb-bc98-468e-bf3a-2482aa47e4dd)
 in Figma:

2024-08-21 19:47 UTC, zeroedin commented on elements/rh-accordion/rh-accordion-header.css
>      var(--_padding-block-end)
```
.toggle { width: 100% }
```
is the issue.

2024-08-22 20:06 UTC, adamjohnson commented on elements/rh-footer/rh-footer-lightdom.css
> +:is(rh-footer) a[slot^="logo"] > img {
I submitted a fix for this linting error upstream: https://github.com/RedHat-UX/red-hat-design-system/pull/1777

2024-08-25 08:53 UTC, bennypowers commented on elements/rh-accordion/rh-accordion-header.ts
>  import { property } from 'lit/decorators/property.js';
if that's the case then it seems we should restore the button element in the shadow root

2024-08-25 09:31 UTC, bennypowers commented on elements/rh-accordion/rh-accordion-header.css
i restored the `<button>` in shadow root, styles for that already existed

2024-08-25 09:46 UTC, bennypowers commented on elements/rh-accordion/rh-accordion-header.ts
>  import { property } from 'lit/decorators/property.js';
I restored the shadow `<button>`, as a result, I had to change the type parameter of the tabindex controller to HTMLButtonElement, which required some fancy footwork with `hasUpdated`, yadda yadda. Also had to move some event listeners around to appease the a11y linter, which i think should all be improvements. firefox' audit still complains that there are buttons on the page with [tabindex=-1] but i think that's a false positive, cause, y'know, rti

I added a heading level controller for when the headers are not wrapped

playwright's ax tree doesn't expose aria-level so i had to fall back to `.is.accessible()`

2024-08-25 10:23 UTC, bennypowers commented
> I'm still seeing the wrong text style in this branch's demos when I open them in a separate tab. The font size should be 18px (`--rh-font-size-body-text-lg`). Weight should be medium (`--rh-font-weight-body-text-medium`).
> 
> I'm also seeing a space below the heading text, which may be because the text isn't large enough to fill that space. Here's what spacing looks like with the caret icon using the updated Brand icon ![Screenshot 2024-08-20 at 3 19 02 PM](https://private-user-images.githubusercontent.com/95588923/359616493-9cd66cdb-bc98-468e-bf3a-2482aa47e4dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1ODE1ODYsIm5iZiI6MTcyNDU4MTI4NiwicGF0aCI6Ii85NTU4ODkyMy8zNTk2MTY0OTMtOWNkNjZjZGItYmM5OC00NjhlLWJmM2EtMjQ4MmFhNDdlNGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDEwMjEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYzdhOWRlMDQzNTBiNzgxMmNiMmMwOTY0ZThjNzMzZWMxYTY5MGQzOGFkZjdkMjYzMmJjNTQyNjEwNmMyODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7J8CRrBN-jXj1RrIH2fDmRLv3655ktOHwjUWxL0_cuo) in Figma:

I change things so that the heading font-size is always large. this means that now the `large` boolean only changes the padding of the panel, but not the font size of the header. That contradicts the docs:

> ### Sizes
> There are two available sizes and the only difference is the title text size. You can use the Small size on large breakpoints, but not the Large size on small breakpoints due to the potential of long title text wrapping to more than two lines.

2024-08-26 13:42 UTC, merged