fix(button): center play icon in circle
RedHat-UX/red-hat-design-system pull request #1731
Opened 2024-07-30 20:12 UTC by adamjohnson

## What I did

1. Centered the icon in the "play" variant of `<rh-button>`.

## Testing Instructions

1. First, view the "play" variant of `<rh-button>` in production [on uxdot](https://ux.redhat.com/elements/button/demo/variants/).
    * Note how it is not centered in the black circle
2. Now, go to the [variants demo](#) in this DP.
3. Notice how the play icon is now centered in the circle.

## Notes to Reviewers (rounded corners or not?)

If you look at the `<rh-button>` [Figma](https://www.figma.com/design/j7Rjo2W6PLloxOSXQOpll0/Red-Hat-Design-System-library?m=auto&node-id=451-3138), you'll notice the play button does _not_ have rounded corners. [The docs](https://ux.redhat.com/elements/button/) for `<rh-button>` also reflect this.

If you look at the [current implementation](https://ux.redhat.com/elements/button/demo/variants/) of `<rh-button variant="play">` and the [Red Hat Icons Play SVGs](https://red-hat-icons.netlify.app/#ui), they _do_ have rounded corners. 

Should the corners be rounded?

## To Do's

- [ ] Decide whether we should proceed with rounded corners or not for the play icon
- [ ] Update docs accordingly

2024-08-02 16:29 UTC, marionnegp requested changes
Let's remove the rounded corners, so we don't have to change more stuff. The play icon from Brand doesn't round them either.

Can the icon size be `var(--rh-size-icon-02, 24px)`?

2024-08-02 16:38 UTC, marionnegp commented
> The play icon from Brand's updated set doesn't round them either.

Wait, just kidding. I had to zoom in a bunch to see the rounded corners for the new play button icon. Let me know if you need an SVG for the triangle icon.

2024-08-05 19:27 UTC, marionnegp approved these changes

2024-08-05 19:34 UTC, zeroedin approved these changes
Look! Guided to middle!

2024-08-05 19:54 UTC, merged