docs: remove `display: block;` from `<main>`
RedHat-UX/red-hat-design-system pull request #1809
Opened 2024-08-30 18:52 UTC by adamjohnson

A few elements had `main { display: block; }` left over from when the `<main>` tag in the demos was set to `display: grid;`—which caused [some layout issues](https://redhat-internal.slack.com/archives/C05GTN4E82G/p1722367349722359) in certain demos.

## What I did

1. I removed the now-defunct `display: block;` declarations from various demo files.

## Testing Instructions

View the standalone / full page DP demos of the following components and make sure they look normal:

  * `rh-breadcrumb`
  * `rh-card` (promo only)
  * `rh-tile`
  * `rh-video-embed`

2024-08-30 19:37 UTC, markcaron approved these changes
Layout Goof? Trim `<Main>`

2024-08-30 19:41 UTC, adamjohnson commented
> @adamjohnson looks like there's a few linting issues remaining otherwise.

Yup, AFAICT those are upstream. Might just sit on those until they are resolved upstream then merge this. No rush.

2024-08-31 17:11 UTC, bennypowers requested changes
other than rh-badge.css, lgtm

2024-08-31 17:11 UTC, bennypowers commented on elements/rh-badge/rh-badge.css
this would change rh-badge, perhaps this file was included by mistake?

2024-09-05 11:09 UTC, bennypowers approved these changes

2024-09-05 11:19 UTC, merged