fix(health-index): add CSS custom prop to adjust z-index
RedHat-UX/red-hat-design-system pull request #1995
Opened 2024-10-17 15:36 UTC by markcaron

## What I did

1. Added `--rh-health-index-z-index` CSS custom prop to allow implementers to patch/adjust any z-index issues they may have with `<rh-health-index>` and other elements on the page.

Temporary solution to #1959

2024-10-27 09:05 UTC, bennypowers requested changes

2024-10-27 09:05 UTC, bennypowers commented on .changeset/eighty-windows-exist.md
> +"@rhds/elements": patch
this is a minor change

Can we fix this without exposing a new css property? maybe with position: relative on the host element?

2024-11-14 06:30 UTC, bennypowers commented on .changeset/eighty-windows-exist.md
> +"@rhds/elements": patch
1. this is only a problem in chrome

![image](https://github.com/user-attachments/assets/97cf96f7-3854-4056-8208-6a6f148cdc9c)

2. I think we can fix this with `position: relative; z-index: 1` on the container element, without requiring a minor release

![image](https://github.com/user-attachments/assets/6eac7036-14e6-4535-a91d-6ec0052dc1c1)

2025-03-25 13:34 UTC, markcaron commented
@bennypowers nice! Thanks for fixing this.

2025-03-25 13:35 UTC, merged