Docs: All Elements page updates
RedHat-UX/red-hat-design-system pull request #2005
Opened 2024-10-23 11:36 UTC by markcaron

## What I did

1. Updating the All Elements page with new screenshots and CSS tweaks to fix thumbnail/screenshot proportions.

## Testing Instructions

1. Check that everything looks ok on the All Elements page

2024-11-05 19:14 UTC, adamjohnson approved these changes
Lovely Gallery, Tidy Merges

2024-11-05 22:57 UTC, coreyvickery commented
@adamjohnson @markcaron Not sure why, but some images are appearing either stretched or too small. For example, look at `Avatar` vs. `Back to top`. Back to top is tiny, but it appears correctly in the container at 100%. Do some images need to be exported again? cc @gradymcgee

Stretched images:

- [ ] Avatar
- [ ] Badge
- [ ] Breadcrumb
- [ ] Button
- [ ] Call to action
- [ ] Pagination
- [ ] Site status
- [ ] Surface (image is fine, missing [description](https://www.figma.com/proto/MDuTWok7eLzC0fEEWEmOE1/All-elements?page-id=2%3A3&node-id=2-17&node-type=canvas&viewport=124%2C-4533%2C1&t=PR4wHSC74KqRuqZ4-1&scaling=scale-down&content-scaling=fixed))

Squashed images:

- [ ] Dialog
- [ ] Popover
- [ ] Video embed

One last thing, the text under `Make a request` is 16px for some reason, not 18px.

2024-11-05 22:59 UTC, coreyvickery requested changes
Left a comment with edits.

2024-12-09 22:32 UTC, coreyvickery approved these changes

2024-12-10 20:26 UTC, merged