Fix/accordion/update tests fix functionality
RedHat-UX/red-hat-design-system pull request #2035
Opened 2024-11-06 05:02 UTC by zeroedin

## What I did

1. Expanded upon spec tests
2. Corrected `expanded` and `expanded-index` attributes functionality
3. Improved demo naming and added comment to header usage in default demo

- [ ] Add changeset, determine what level of change this is...
  Does this actually change the expected API?  Currently if you add `expanded` to a header it does not unless on `firstUpdated` update the accordions state.  I felt like that was incorrect expectation and that the panel should belong wot the header and expand with it when the header is given `expanded`.  However even PFE accordion you need to add `expanded` to both the header and the panel in order for the pair to be expanded.  Also you can now use `expanded-index` and `expanded` together now as both just feed the `expandedIndexSet`.
  
Closes #2032 
Closes #2019 

## Testing Instructions

1. View Deploy preview demos

## Notes to Reviewers

2024-11-22 16:21 UTC, zeroedin commented
@bennypowers thoughts on the level of change here?

2025-01-28 20:55 UTC, adamjohnson requested changes
👏  Added back tests, nice!

1) Need docs for `expanded` under `rh-accorion-header` and `rh-accordion-panel` on the Code page.
2) Docs for `expanded-index` has an example that references `<pf-accordion>`. It should reference `<rh-accordion>`.
3) If an accordion loads with `expanded-index="0, 2"` and the user changes those values—let's say from `0, 2` to `1`, should these values be reactive?
    * AKA should accordion `0` and `2` _close_ and `1` open?
4) `<rh-accordion-header>` sets `role="heading"` but does not have `aria-level` [as is required](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-level#with_heading_role).
    * Spin this to another PR if it's out of scope.

2025-01-28 20:55 UTC, adamjohnson commented on elements/rh-accordion/demo/rh-accordion.html
> +  <!-- H2 tags will be removed on upgrade, rh-accordion-header will set aria-level internally using the header tag that wraps it -->
Probably best to just have one of these comments instead of repeating it 3x.

2025-01-30 19:52 UTC, zeroedin commented
> If an accordion loads with `expanded-index="0, 2"` and the user changes those values—let's say from `0, 2` to `1`, should these values be reactive?
> * AKA should accordion `0` and `2` _close_ and `1` open?

Yes, it should update, good catch. It appears this doesn't work here but does in PFE.  I'll retake a look at it.

2025-01-30 19:53 UTC, zeroedin commented
> `<rh-accordion-header>` sets `role="heading"` but does not have `aria-level` [as is required](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-level#with_heading_role).
> * Spin this to another PR if it's out of scope.

If this happens in the current demos on `ux.`  please spin this out into another issue!

2025-02-09 08:29 UTC, bennypowers commented on elements/rh-accordion/demo/rh-accordion.html
> +  <!-- H2 tags will be removed on upgrade, rh-accordion-header will set aria-level internally using the header tag that wraps it -->
```suggestion
  <!-- H2 tags will be removed on upgrade, rh-accordion-header will set the correct heading level internally using the header tag that wraps it -->
```

2025-02-10 21:05 UTC, adamjohnson commented
> If this happens in the current demos on `ux.` please spin this out into another issue!

Done: https://github.com/RedHat-UX/red-hat-design-system/issues/2161.

2025-02-10 21:10 UTC, adamjohnson commented on elements/rh-accordion/demo/expanded-attribute.html
> +  <h2><rh-accordion-header expanded>Item Two</rh-accordion-header></h2>
When I load [the DP demo](https://deploy-preview-2035--red-hat-design-system.netlify.app/elements/accordion/demo/expanded-attribute/), this panel is not expanded. I'm guessing it should be, yes?

2025-02-11 09:36 UTC, bennypowers requested changes

2025-04-03 17:52 UTC, bennypowers commented
Bunch of unrelated changes got merged in. Checkout their versions from cubone into this branch

2025-04-04 23:22 UTC, zeroedin commented on elements/rh-accordion/demo/expanded-attribute.html
> +  <h2><rh-accordion-header expanded>Item Two</rh-accordion-header></h2>
@adamjohnson please review again when you have a chance

2025-04-04 23:24 UTC, zeroedin commented on elements/rh-accordion/rh-accordion-header.ts
> +    this.#belongsTo = this.closest<RhAccordion>('rh-accordion');
wrapped this in an `!isServer` for now.  I looked at using context and ran into an issue with sending a `this` reference. I was trying to figure out how to send a reference to the parent accordion but ran out of ideas, lets discuss in office hours..

2025-04-04 23:24 UTC, zeroedin commented on elements/rh-accordion/rh-accordion-header.ts
>      const heading = this.closest('h1,h2,h3,h4,h5,h6');
wrapped this in an `!isServer` for now.

2025-04-04 23:25 UTC, zeroedin commented
@bennypowers functionality of the demos is now corrected, please give this another review, feel free to tackle anything left as you see fit and we can discuss in office hours on monday.

2025-04-06 06:28 UTC, bennypowers commented on .changeset/smart-swans-move.md
> +`<rh-accordion>`: corrected use of `expanded-index` and `expanded`
```suggestion
`<rh-accordion>`: `expanded` and `expanded-index` attributes work as expected
```

2025-04-06 06:28 UTC, bennypowers approved these changes

2025-04-06 06:29 UTC, merged