fix(accordion): correct header text font weight
RedHat-UX/red-hat-design-system pull request #2084
Opened 2024-12-10 15:01 UTC by zeroedin

## What I did

1. Corrected header text font-weight

## Testing Instructions

1. View Deploy Preview, Safari, Firefox, and Chrome should have the same font-weight.

## Notes to Reviewers

2024-12-10 15:31 UTC, bennypowers requested changes

2024-12-10 15:31 UTC, bennypowers commented on .changeset/purple-drinks-double.md
> +<rh-accordion>`: corrected accordion header text font weight
```suggestion
`<rh-accordion>`: corrected accordion header text font weight
```

2024-12-10 15:43 UTC, zeroedin commented on .changeset/purple-drinks-double.md
> +<rh-accordion>`: corrected accordion header text font weight
oops good catch copy/paste fail.

2024-12-10 21:30 UTC, marionnegp reviewed
Heading weights look great in Chrome, Firefox, Safari, and Edge on my Mac.

In Safari, I'm seeing duplicated and empty accordions in the demos. I added a couple screenshots below. Would you want this created as a separate issue?

Here's the default accordion demo:
![Screenshot 2024-12-10 at 4 21 38 PM](https://github.com/user-attachments/assets/829cbe48-bc81-439e-adad-3317060ddcb2)

This is the nested accordion demo (+ crazy icon duplication in the CTA):
![Screenshot 2024-12-10 at 4 23 31 PM](https://github.com/user-attachments/assets/bc9edc06-a744-4e2a-814a-b311e3eba6a8)

2024-12-11 04:16 UTC, bennypowers approved these changes

2024-12-11 04:17 UTC, bennypowers commented
@marionnegp that's a separate issue, affects all SSR demos in safari

2024-12-11 04:19 UTC, merged