fix(audio-player): use rh-icon instead of custom svg for scrubbers
RedHat-UX/red-hat-design-system pull request #2095
Opened 2024-12-16 19:21 UTC by zeroedin

## What I did

1.  Replaced custom svg's with `rh-icon` for scrubbers

Closes #2049

### TODO:

- [ ] Docs images as listed in issue

## Testing Instructions

1. View deploy preview

## Notes to Reviewers

@marionnegp I added the rh-icon with the same size as the play button (24px) as that looked closest to the previous state. If it should be a different size let me know.  I'll leave PR in draft and if you want to make the changes to the docs images on this same branch go right ahead.

2024-12-17 18:50 UTC, marionnegp requested changes
The scrubber icon size looks good to me!

- [ ] Can the disabled scrubber buttons be `--rh-color-gray-30` (light theme) and `--rh-color-gray-50` (dark theme) for now? (We'll eventually add disabled color tokens.)

The rest of these can be updated in a separate PR if you'd prefer:

- [ ] Speed controls don't seem to be using the right color in dark theme.
![Screenshot 2024-12-17 at 12 17 32 PM](https://github.com/user-attachments/assets/a9ff4722-8218-4089-b3cb-c2c2d7ab3ca1)

- [x] Play button in light theme player should be in a `darkest` circle with a white play icon:
![Screenshot 2024-12-17 at 12 20 53 PM](https://github.com/user-attachments/assets/8f991526-785f-4155-b4f4-54438dd1cd07)

- [ ] Play button in dark theme player should be in a white circle with a `darkest` play icon:
![Screenshot 2024-12-17 at 12 22 23 PM](https://github.com/user-attachments/assets/e84193c6-b245-4f56-a247-ec5bd4564ad6)

2024-12-17 21:20 UTC, zeroedin commented
> * Speed controls don't seem to be using the right color in dark theme.

This looks like it opens up a bigger issue on audio player.  Will need to dig deeper tomorrow to see what is going on, Color context from the outside leaks into audio player and it has an internal surface which doesn't set to match the parent context:

Example of issue:
```html
<rh-context-demo color-palette="darkest"> <!--sets context to dark-->
  <rh-audio-player> <!-- dark background get set -->
    <!-- shadowroot-->
       <rh-surface> <!-- internal context is set to light (note no color palette) -->
          Text / Buttons <!-- all think they are on a light background -->
   </rh-audio-player>
 </rh-context-demo>
 ```

2024-12-18 20:21 UTC, zeroedin commented
@bennypowers I can't believe the resolution was as simple as removing the `rh-surface` from the shadow root. However, I couldn't find a reason for it. Can you double-check me here? I may be overlooking something.

2024-12-18 20:24 UTC, zeroedin commented
> Play button in light theme player should be in a darkest circle with a white play icon:

@marionnegp, I'll look at these changes with the circle not being present on the play icon now. The circle was likely part of the custom SVG previously.

2024-12-18 20:32 UTC, zeroedin commented
> The circle was likely part of the custom SVG previously.

This was not a true statement 😆 , that said I'm now adjusting the variables used directly based on the context.

```css
#play,
#full-play {
  border-radius: 50%;
  background-color: var(--rh-color-surface-darkest, #151515);
  color:
    var(--rh-audio-player-icon-background-color,
      var(--rh-color-text-primary-on-dark, #ffffff));
}

.dark {
  #play,
  #full-play {
    background-color: var(--rh-color-surface-lightest, #ffffff);
    color:
      var(--rh-audio-player-icon-background-color,
        var(--rh-color-text-primary-on-light, #151515));
  }
}
```

2024-12-18 20:38 UTC, zeroedin commented
![image](https://github.com/user-attachments/assets/a16b154c-031b-4ea1-99e8-0fb2b86299f5)

Another bug found, the highlight in the text being read in the transcript also appears to be off. 

Does not appear to be new / introduced in this PR either, [also found on ux.redhat.com](https://ux.redhat.com/elements/audio-player/demo/mini/)

![image](https://github.com/user-attachments/assets/2932f6c8-7b86-4879-887f-8d65a92de3d1)

2024-12-19 14:53 UTC, zeroedin commented
> I think we've talked about this before somewhere. Déjà vu?

It was in `rh-video-embed.` it looks like the difference is we need to use an `rh-button variant="play"` which will get us the adjusted variant we are looking for. Looking to see if we can reuse that here.

2024-12-19 15:05 UTC, marionnegp commented
> Another bug found, the highlight in the text being read in the transcript also appears to be off.

The docs show images of the [highlight](https://ux.redhat.com/elements/audio-player/features/#highlighting) for light theme, and that blue looks most like `--rh-color-blue-20`. @coreyvickery, did you specify a highlight color for light and dark themes?

Looking at Nikki's original [audio player PR](https://github.com/RedHat-UX/red-hat-design-system/pull/679) and the [transcript demo](https://deploy-preview-679--red-hat-design-system.netlify.app/elements/audio-player/demo/detailed-transcript/), it might have been using the default browser highlight. Maybe this was a bug introduced when we made changes to the theming?

2024-12-19 15:22 UTC, zeroedin commented
> Maybe this was a bug introduced when we made changes to the theming?

I believe that is the case, yes.

2024-12-19 15:27 UTC, zeroedin commented on elements/rh-audio-player/rh-audio-player.css
> +  }
I don't like doing this, but I must override an internal CSS variable in the rh-button to match the Figma styles. @bennypowers, as you suggested, we can break this out into a separate issue. Maybe go with the broken styles while still using the `rh-button variant="play"` in this PR. @marionnegp, what are your thoughts?

2024-12-19 16:22 UTC, zeroedin commented on elements/rh-audio-player/rh-audio-player.css
> +  }
After a discussion with @marionnegp we are going to back out of the usage of `rh-button variant=play` for now and reimplement the styles needed to adjust the icon that is already in rh-button so we can release this PR still as a patch. There was another issue with this approach, and that is that the `rh-button variant=play` doesn't support swapping its icon to a pause button easily, even if we can just use the part to override the background colors necessary for audio-player.

2025-05-23 19:09 UTC, zeroedin commented
Given changes in theming between the opening of this PR and its becoming stale, I recommend closing this PR in favor of opening a newly cut branch of the current state main to deal with this issue and reimplement the changes instead of dealing with the conflicts that are bound to happen here.  Leaving it open till a new PR is cut that references this one.

2025-07-08 17:01 UTC, zeroedin commented
Close in favor of: https://github.com/RedHat-UX/red-hat-design-system/pull/2469

2025-07-08 17:01 UTC, closed without merging