feat(rh-footer): RHDC styling fixes
RedHat-UX/red-hat-design-system pull request #304
Opened 2022-05-23 20:49 UTC by heyMP

## What I did

1. Ported styles from `@patternfly/pfe-styles/pfe-base.css`.  `pfe-base.css` has a mixed bag of styles that have negative consequences.

## Testing instructions

1.  Checkout the `feat/proxy` branch. We are going to use the proxy server to test styles on RHDC.
2. Start dev server `npm run dev`
3. Start the proxy server in a separate process `npm run proxy`
4. Open the the proxy url http://localhost:8001
5. Scroll to the bottom and you should see the rh-footer in context of the RHDC site.
6. Ensure it matches the footer in the dev server http://localhost:8000/demo/rh-footer/

## Development instructions

1. Save all of your changes to the `feat/footer-style-tweaks`

## Todos

- [x] Port a styles from `pfe-base.css`
- [ ] Add CSS overrides / resets for header & ul styles

2022-05-23 21:20 UTC, heyMP commented
- [x] Port a styles from pfe-base.css
![Screen Shot 2022-05-23 at 5 17 57 PM](https://user-images.githubusercontent.com/3428964/169907732-6d575b77-6990-4631-9b16-b02d77866301.png)

2022-05-24 08:08 UTC, bennypowers requested changes

2022-05-24 08:08 UTC, bennypowers commented on elements/rh-footer/rh-footer-lightdom.css
> +  color: var(--pfe-broadcasted--link, #06c);
these should be `--rh-`, it's our party :)

```suggestion
  color: var(--rh-color-link-inline-on-light, var(--rh-color-blue-500, #06c));
```

2022-05-24 08:08 UTC, bennypowers commented on elements/rh-footer/rh-footer-lightdom.css
> +  color: var(--pfe-broadcasted--link--hover, #004080);
```suggestion
  color: var(--rh-color-link-inline-hover-on-light, var(--rh-color-blue-600, #004080));
```

2022-05-24 08:08 UTC, bennypowers commented on elements/rh-footer/rh-footer-lightdom.css
> +  color: var(--pfe-broadcasted--link--focus, #004080);
```suggestion
  color: var(--rh-color-link-inline-hover-on-light, var(--rh-color-blue-600, #004080));
```

2022-05-24 08:08 UTC, bennypowers commented on elements/rh-footer/rh-footer-lightdom.css
> +  color: var(--pfe-broadcasted--link--visited, #6753ac);
```suggestion
  color: var(--rh-color-link-inline-visited-on-dark, var(--rh-color-purple-300, #a18fff));
```

2022-05-24 08:08 UTC, bennypowers commented on elements/rh-footer/rh-footer-lightdom.css
> +  text-decoration: var(--pfe-broadcasted--link-decoration, none);
```suggestion
  text-decoration: none;
```

2022-05-24 08:08 UTC, bennypowers commented on elements/rh-footer/rh-footer-lightdom.css
> +  text-decoration: var(--pfe-broadcasted--link-decoration--focus, underline);
```suggestion
  text-decoration: underline;
```

2022-05-24 10:57 UTC, bennypowers approved these changes

2022-05-24 10:59 UTC, merged