RHDS rh-tooltip
RedHat-UX/red-hat-design-system pull request #465
Opened 2022-08-10 16:28 UTC by brianferry

## What I did

1.

## Testing Instructions

1.

## Notes to Reviewers

2022-08-15 15:35 UTC, brianferry commented
@marionnegp - Would you be available to take a look at the demo at https://deploy-preview-465--red-hat-design-system.netlify.app/components/tooltip/demo/ and confirm that it matches https://ux.redhat.com/components/tooltip/ ?

2022-08-15 18:19 UTC, marionnegp commented
- [ ] Padding is showing up as 14px, but I see that you have it set to 1em. Should be 16px.
- [ ] Arrow size should be 16px wide x 9px tall.
- [ ] Space between the top and bottom tooltips and their buttons is 10px. Should be 12px. (Left and right tooltips look right!)

I don't think we specified a max-width in our docs, but what you have looks good to me.

2022-08-16 16:23 UTC, bennypowers requested changes

2022-08-16 16:23 UTC, bennypowers commented on elements/rh-tooltip/rh-tooltip.ts
> +@customElement('rh-tooltip') @pfelement()
```suggestion
@customElement('rh-tooltip')
```

2022-08-16 16:23 UTC, bennypowers commented on elements/rh-tooltip/rh-tooltip.ts
> +import { pfelement, colorContextConsumer } from '@patternfly/pfe-core/decorators.js';
```suggestion
import { colorContextConsumer } from '@patternfly/pfe-core/decorators.js';
```

2022-08-16 17:21 UTC, bennypowers commented on elements/rh-tooltip/rh-tooltip.css
> +  --pf-c-tooltip--BoxShadow: 0 0.125rem 0.25rem 0 rgba(21, 21, 21, 0.2);
reserving this comment pending @marionnegp's design review.

Resolve this (and any subsequent) comment threads to auto-merge

2022-08-16 17:21 UTC, bennypowers approved these changes

2022-08-17 16:14 UTC, marionnegp commented
I double checked the spacing between the tooltip and the invoker, and it's actually supposed to be 8px. Sorry for saying it was 10px! It looks like the spacing is only 1px off for the tooltips, but I couldn't tell without taking screenshots and zooming in. 

The tooltip looks good to me.

2022-08-17 18:17 UTC, brianferry commented
@marionnegp - No worries at all, should be fixed now.

2022-08-17 20:06 UTC, marionnegp approved these changes

2022-08-17 20:14 UTC, merged

2022-08-18 06:33 UTC, bennypowers commented
Congrats on the merge @brianferry