feat(tag): add <rh-tag>
RedHat-UX/red-hat-design-system pull request #597
Opened 2022-10-20 23:06 UTC by zeroedin

## What I did

1. Created `rh-tag` based on `BaseLabel` from pfe-label
2. Closes #398  
 
### Design spec:
https://xd.adobe.com/view/d20a1c17-375c-4c7f-6827-5fe2f8c2d92f-a43b/screen/6a1953ee-4519-43d3-b02e-13453611c015/specs/

### Todo:

- [x] write spec tests
- [x] add changeset
- [x] rename `rh-tag`

## Testing Instructions

1. `npm start`
2. `npm run watch:docs`
3. View deploy preview

## Notes to Reviewers

2022-11-17 08:01 UTC, bennypowers commented
i'm concerned about the use of the word `label` here.

Can we make a FACE that acts like `<label>`?

```html
<rh-label for="switch">AT reads me as label for switch</rh-label>
<rh-switch id="switch"></rh-switch>
```

Until we're sure we can do that (perhaps with cross-root aria and element internals?) I think we should consider renaming this element.

cc @markcaron @hellogreg @nikkimk

2022-11-17 13:45 UTC, zeroedin commented
> i'm concerned about the use of the word `label` here.


`rh-tag` maybe to remove the confusion with a potential FACE element?  

I'm trying to figure out why we'd need to build `rh-label` as a FACE element that mimics the standard `<label>` tag, but enforcement of styles maybe enough of a reason.

2022-11-17 17:52 UTC, bennypowers commented
> why we'd need to build `rh-label` as a FACE element that mimics the standard `<label>` tag

`label` means something specific on the web. it's critical that we preserve the semantic meaning of label as "element or attribute containing text which describes a control or other element".

2022-12-01 16:15 UTC, zeroedin commented
@coreyvickery when you have a chance could you weigh in here?  We would need to revise the naming in the XDs and future docs on `ux.` so you have the veto power here on this.  We would like to resolve this as soon as we can so can move forward with this PR as it's been sitting for a while now.

The plan is `rh-tag` (or whatever we name this component) would still extend `pfe-label`, opening up `rh-label` namespace for a future new component that would be a Form Associated Custom Element, using element internals that more resembles the `<label>` HTML tag and use case.

2022-12-01 20:33 UTC, coreyvickery commented
@zeroedin Fine with that, as long as `rh-tag` can incorporate the styles seen in the link at the top.

2022-12-03 16:22 UTC, bennypowers requested changes

2022-12-03 16:22 UTC, bennypowers commented on elements/rh-tag/README.md
>  Add a description of the component here.
this file needs some attention

2022-12-03 16:22 UTC, bennypowers commented on elements/rh-tag/demo/rh-tag.html
> +  <h2 slot="header">Filled Color</h2>
```suggestion
  <h2>Filled Color</h2>
```
etc

2022-12-03 16:22 UTC, bennypowers commented on elements/rh-tag/demo/rh-tag.html
> +      <pfe-codeblock><div codeblock-container code-language="html"><code>&lt;rh-tag color="blue"&gt;Blue&lt;/rh-tag&gt;</code></div></pfe-codeblock>
let's prefer `<zero-md>`

2022-12-12 13:05 UTC, merged