Get started section changes 01 06
RedHat-UX/red-hat-design-system pull request #704
Opened 2023-01-17 08:28 UTC by coreyvickery

## What I did

1. Updated icon and logo page copy (and titles) per new brand asset CC libraries
2. Cleaned up `Get started`, `Design system kit`, and `FTS starter kit` pages per the above as well (rewrote language for better UX, updated old/outdated images, etc.)

## Notes to Reviewers

I only need feedback on the icon and logo pages, but if you have time to skim the other pages, that's great.

2023-01-17 21:25 UTC, marionnegp requested changes
I skimmed each page, and changes look good! I left a comment about writing out the name of the XD libraries for accessibility. 

There are also some pages that use "this page" or "this form" as links that point to different URLs. I think giving each link a more specific label would help users with screen readers.

2023-01-17 21:25 UTC, marionnegp commented on docs/get-started/icon-libraries.njk
> +  <p>To request access to the Adobe CC libraries containing brand assets, fill out <a href="https://docs.google.com/forms/d/e/1FAIpQLSeZbyEh0CGJrujIocHuR4ZMWh_uew-IeUNWewBOb3GBnUHTrA/viewform?usp=sf_
The titles of the three libraries should be listed out as text, instead of just being shown as an image.

2023-01-17 21:25 UTC, marionnegp commented on docs/get-started/product-logo-library.njk
> +  <p>To request access to the Adobe CC libraries containing brand assets, fill out <a href="https://docs.google.com/forms/d/e/1FAIpQLSeZbyEh0CGJrujIocHuR4ZMWh_uew-IeUNWewBOb3GBnUHTrA/viewform?usp=sf_
The titles of the three libraries should be listed out as text, instead of just being shown as an image.

2023-01-18 09:25 UTC, coreyvickery commented
@marionnegp Thanks, the copy has been updated. Please review again if needed and suggest further changes or go ahead and approve.

2023-01-18 15:01 UTC, marionnegp reviewed
Added some suggestions for rewording sentences so that we have more unique link text on the icon and logo pages.

2023-01-18 15:01 UTC, marionnegp commented on docs/get-started/product-logo-library.njk
> +  <p>To learn more about what assets are available in each library and how to find them in your Adobe CC apps, visit <a href="https://docs.google.com/presentation/d/11iqtI1ew6lAiUHXHY8u7nxUWOppg0n9W5
Reword to `To learn more about what assets are available in each library and how to find them in your Adobe CC apps, view <a href="https://docs.google.com/presentation/d/11iqtI1ew6lAiUHXHY8u7nxUWOppg0n9W51Kj1CCFhBA/edit?usp=sharing&urp=gmail_link">these instructions</a>.`

2023-01-18 15:01 UTC, marionnegp commented on docs/get-started/product-logo-library.njk
> +  If you are having trouble locating a product logo in the library, <a href="mailto:brand@redhat.com">contact</a> the Brand team.</p>
Link "contact the Brand team" instead of only "contact"

2023-01-18 15:01 UTC, marionnegp commented on docs/get-started/product-logo-library.njk
> +  To request a new product logo, <a href="mailto:brand@redhat.com">contact</a> the Brand team.</p>
Link "contact the Brand team" instead of only "contact"

2023-01-18 15:01 UTC, marionnegp commented on docs/get-started/product-logo-library.njk
> +  New assets are added about once per month, however, sometimes product logos are not included in that release. Updates to our libraries are communicated over e-mail and if you want to be added to th
Link "contact the Brand team" instead of only "contact"

2023-01-18 16:16 UTC, marionnegp approved these changes
Changes look good

2023-01-18 16:25 UTC, merged