fix: added rh-accordion styles in footer
RedHat-UX/red-hat-design-system pull request #742
Opened 2023-02-20 17:53 UTC by heyMP

## What I did

1.

## Testing Instructions

1.

## Notes to Reviewers

2023-02-20 17:58 UTC, bennypowers commented on .changeset/spotty-moose-draw.md
> +asdf
hhjkl;

2023-02-20 18:22 UTC, heyMP commented on .changeset/spotty-moose-draw.md
> +asdf
sorry, it was suppose to be `wasd` :)

2023-02-20 19:22 UTC, bennypowers approved these changes

2023-02-20 19:26 UTC, heyMP commented
@RedHat-UX/designers could you take a look at the branch tests and approve that these fixes are appropriate?

2023-02-20 20:03 UTC, coreyvickery commented
@heyMP Small nitpick, but it almost looks like the border on the right is 2px instead of 1px.

<img width="21" alt="Screen Shot 2023-02-20 at 12 03 13 PM" src="https://user-images.githubusercontent.com/45767595/220189955-bd27587a-12d1-4921-90e3-fa299c3e4b65.png">

2023-02-20 22:48 UTC, heyMP commented
@coreyvickery I fixed the issue in rh-accordion.  Can you check it now?

- [x] border on the right is 2px instead of 1px.

2023-02-21 04:11 UTC, bennypowers requested changes
2 small technical nits

2023-02-21 04:11 UTC, bennypowers commented on elements/rh-accordion/rh-accordion-header.css
> +  border-inline-end: 1px solid var(--_border-inline-end-color, #d2d2d2);
Use token

2023-02-21 04:11 UTC, bennypowers commented on .changeset/spotty-moose-draw.md
> +`<rh-accordion>`: fixed double border on expanded state
Should be it's own changeset

2023-02-21 06:33 UTC, bennypowers approved these changes

2023-02-21 08:42 UTC, coreyvickery approved these changes

2023-02-21 08:43 UTC, coreyvickery commented
@heyMP Approved on my end.

2023-02-21 09:45 UTC, merged