fix(cta) arrow/icon
RedHat-UX/red-hat-design-system pull request #840
Opened 2023-03-23 21:36 UTC by nikkimk

## What I did

1. made static icon size
2. positioned icon inline instead of flex

## Notes to Reviewers
I think this addresses what we were talking about. If not, I'm happy to change it.

2023-03-24 11:35 UTC, bennypowers requested changes
Is this a dupe of #835 ?

PTAL @zeroedin

2023-03-24 11:35 UTC, bennypowers commented on .changeset/little-hairs-rhyme.md
> +`<rh-cta>`: made static icon size and positioned icon inline instead of flex
changesets should describe user-facing improvements, not internal code changes. This prose could be a commit message, or a PR title, but shouldn't be in the changelog

2023-03-24 11:54 UTC, bennypowers commented on .changeset/little-hairs-rhyme.md
> +`<rh-cta>`: made static icon size and positioned icon inline instead of flex
Could you also please update the PR title? I couldn't figure out which problem this is coming to address

2023-03-24 13:16 UTC, bennypowers requested changes

2023-03-24 13:16 UTC, bennypowers commented on .changeset/little-hairs-rhyme.md
> +`<rh-cta>`: made static icon size and positioned icon inline instead of flex
```suggestion
`<rh-cta>`: ensured that arrow in default CTAs is aligned to the end of the last line of text
```

2023-03-24 13:17 UTC, bennypowers commented on .changeset/little-hairs-rhyme.md
> +`<rh-cta>`: made static icon size and positioned icon inline instead of flex
very clear. thanks! This is #238

2023-03-24 13:53 UTC, marionnegp reviewed
I'm still seeing the arrow flow to its own line sometimes.
![Screenshot 2023-03-24 at 9 51 40 AM](https://user-images.githubusercontent.com/95588923/227539682-2cd6fa6e-6cfb-4f8b-bbe6-e8d9091067df.png)

![Screenshot 2023-03-24 at 9 50 38 AM](https://user-images.githubusercontent.com/95588923/227539590-4b096d52-a2a5-4f7a-8bb0-7351caa31268.png)
![Screenshot 2023-03-24 at 9 45 17 AM](https://user-images.githubusercontent.com/95588923/227539591-83f2d034-14aa-4e90-8680-557d1176df92.png)
fc665-d9f2-4791-a5ca-d3f597d5cc7b.png)

2023-03-24 16:21 UTC, nikkimk commented
@marionnegp try it now

2023-03-24 16:23 UTC, zeroedin commented
> @marionnegp try it now

Does it look like the arrow is resting slightly too far down?  Like `vertical-align: baseline` look more correct?

2023-03-24 16:35 UTC, zeroedin approved these changes
Looney Groovy Toony Moony

2023-03-26 07:48 UTC, bennypowers commented on elements/rh-cta/rh-cta.css
> +  padding-inline-end: --_arrow-size);
```suggestion
  padding-inline-end: var(--_arrow-size);
```

2023-03-27 18:05 UTC, bennypowers commented
Tests are red ptal

2023-03-27 18:48 UTC, marionnegp approved these changes
Arrow placement looks good to me!

2023-03-27 18:58 UTC, bennypowers approved these changes

2023-03-27 18:58 UTC, merged