fix(tabs): add randomId attributes
RedHat-UX/red-hat-design-system pull request #954
Opened 2023-04-26 04:25 UTC by zeroedin

## What I did

1. Added `getRandomId` to tab and panels for aria accessibility upgrade

## Testing Instructions

1.

## Notes to Reviewers

2023-04-26 19:02 UTC, nikkimk approved these changes
lgtm

2023-04-27 07:43 UTC, bennypowers requested changes
Should do the assignment in connectedCallback

2023-04-27 07:43 UTC, bennypowers commented on elements/rh-tabs/rh-tab-panel.ts
> +  id: string = this.id || getRandomId(this.localName);
Skills go in connected carnal and use ||=

2023-04-27 07:44 UTC, bennypowers commented on .changeset/nine-trainers-flash.md
> +`rh-tabs`: added id attributes to tabs and panels when not provided
```suggestion
`<rh-tabs>`: improve accessibility by assigning a random id when one is not provided
```

2023-04-27 08:30 UTC, bennypowers commented
Would we rather do this in pfe?

2023-04-27 11:24 UTC, zeroedin commented
> Would we rather do this in pfe?

Now that you bring it up, yes makes sense to do it in Base Classes of PfE.

2023-04-27 11:25 UTC, closed without merging

2023-04-27 11:26 UTC, zeroedin commented
> consider https://github.com/patternfly/patternfly-elements/pull/2487 as an alternative (we're anyways planning a release in https://github.com/patternfly/patternfly-elements/pull/2481)

Closed in lieu of the above alternative