fix(tabs): reduce overflow scroll button padding
RedHat-UX/red-hat-design-system pull request #956
Opened 2023-04-26 18:38 UTC by zeroedin

## What I did

1. Reduced padding on the overflow scroll buttons from `--rh-spacer-xl: 24px` to `--rh-spacer-lg: 16px`

## Testing Instructions

1. View [Deploy Preview](https://deploy-preview-956--red-hat-design-system.netlify.app/elements/tabs/demo/)

2023-04-27 09:52 UTC, bennypowers requested changes

2023-04-27 09:52 UTC, bennypowers commented on .changeset/neat-pumas-peel.md
> +`rh-tabs`: reduced padding on overflow scroll buttons
```suggestion
`<rh-tabs>`: reduced padding on overflow scroll buttons
```

2023-04-27 09:52 UTC, bennypowers approved these changes

2023-05-02 17:44 UTC, zeroedin commented
awaiting updated/finalized specs from @coreyvickery

2023-05-02 17:58 UTC, zeroedin commented
Should also make sure this change is implemented in `rh-subnav` to ensure look and feel consistency.

2023-05-05 13:31 UTC, zeroedin commented
updated xd spec: https://xd.adobe.com/view/e0eb07d2-71ac-498f-9d74-b872dd7c204b-b5b8/

2023-05-05 13:58 UTC, merged