docs(badge): badge docs cleanup
RedHat-UX/red-hat-design-system pull request #966
Opened 2023-05-02 17:40 UTC by nikkimk

## What I did

1. Updated badge docs.

## Testing Instructions

1. View DP badge docs.
2. Compare to [Badge doc](https://docs.google.com/document/d/1arJJbhGj3nLxWRzCVH67dhJnpkzHAjgGk57a764YTx0/edit#heading=h.aixz6587nrdt) and to [Docs cleanup checklist](https://github.com/RedHat-UX/red-hat-design-system/wiki/Docs-Cleanup-Q2-2023-Checklist).

## Notes to Reviewers
The following are WIP to be addressed as other issues/PRs:
- related items list
- sample element live example
- ARIA Authoring Practices Guide (APG) 
- Further learning / resources

2023-05-04 07:09 UTC, bennypowers requested changes

2023-05-04 07:09 UTC, bennypowers commented on .changeset/red-melons-begin.md
> +Added a summary to `<rh-badge>`
```suggestion
`<rh-badge>`: corrected and updated custom elements manifest
```

2023-05-04 07:09 UTC, bennypowers commented on elements/rh-badge/rh-badge.ts
can we add in `@cssprop`s here, too?

2023-05-04 07:16 UTC, bennypowers requested changes

2023-05-04 07:16 UTC, bennypowers commented on elements/rh-badge/rh-badge.ts
>     * Denotes the state-of-affairs this badge represents
we should specify the semantic meaning of each option here
```suggestion
   * Denotes the state-of-affairs this badge represents
   * - **info**: yadda yadda
   * - **success**: etc etc
```

Need @coreyvickery's design input on that

2023-05-31 20:06 UTC, bennypowers commented on elements/rh-badge/docs/20-guidelines.md
> +If you need to add specific text captions to elements, consider using a <a href="/elements/tag">Tag</a> instead.
```suggestion
If you need to add specific text captions to elements, consider using a [Tag](/elements/tag/) instead.
```

2023-05-31 20:07 UTC, bennypowers commented on elements/rh-badge/docs/20-guidelines.md
>  The width of a badge varies based on the counter number. Using a number larger than the threshold will display a + at the end. For example, if <code>999</code> is the threshold, using <code>1,000</co
```suggestion
The width of a badge varies based on the counter number. Using a number larger than the threshold will display a + at the end. For example, if `999` is the threshold, using `1,000` or larger will display `999+`.
```

prefer markdown syntax

2023-06-01 16:55 UTC, bennypowers commented on elements/rh-badge/docs/10-style.md
> +| ![8 pixel spacer]({{ '../badge-8px-spacer.png' | url }}){width=8} | `8px 0.5rem`  |
must #949

2023-06-02 19:28 UTC, nikkimk commented
@bennypowers PTAL
@coreyvickery Also TAL

2023-06-02 19:30 UTC, coreyvickery commented
@nikkimk Looks fine.

2023-06-02 19:31 UTC, coreyvickery approved these changes
Looks good.

2023-06-04 06:31 UTC, bennypowers requested changes

2023-06-04 06:31 UTC, bennypowers commented on docs/_includes/accessibility/1.4.1-A.md
> +- [SC 1.4.1 Ise of Colot](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html) (Level A)
```suggestion
- [SC 1.4.1 Use of Color](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html) (Level A)
```

2023-06-04 06:31 UTC, bennypowers commented on elements/rh-badge/docs/20-guidelines.md
> +{% alert title="Warning" %}
```suggestion
{% alert title="Warning", state="warning" %}
```

2023-06-05 13:21 UTC, bennypowers approved these changes

2023-06-05 13:26 UTC, merged