Docs/tooltip
RedHat-UX/red-hat-design-system pull request #972
Opened 2023-05-03 18:55 UTC by nikkimk

## What I did

1. Updated tooltip docs.

## Testing Instructions

1. View [DP tooltip docs]().
2. Compare to [tooltip doc](https://docs.google.com/document/d/1HUa31FFVjv0Sl1qSt0qABqLyBsJ5hcL8ByxlT5Bg2Ko/edit#) and to [Docs cleanup checklist](https://github.com/RedHat-UX/red-hat-design-system/wiki/Docs-Cleanup-Q2-2023-Checklist).

## Notes to Reviewers
The following are WIP to be addressed as other issues/PRs:
- Related items list
- Sample element / live example
- Accessibility tab
- Code tab styling

2023-05-04 07:08 UTC, bennypowers requested changes

2023-05-04 07:08 UTC, bennypowers commented on .changeset/nasty-flies-flash.md
> +Added a summary to `<rh-tooltip>`
```suggestion
`<rh-tooltip>`: corrected and updated custom elements manifest
```

2023-05-04 07:08 UTC, bennypowers commented on elements/rh-tooltip/rh-tooltip.ts
>   * @slot - Place element content here
can we add in the `@cssprops` here, too, or is that out of scope?

2023-05-04 08:04 UTC, bennypowers commented
apologies for adding unrelated changes here, but one thing led to another:
- the bem-style css props in tooltip were contrary to guidelines, so we need a minor release to fix them
- that introduced css linting issues which needed to be addressed 
- fixing those opened up the opportunity to apply more consistent formatting across the repo

the changes outside of tooltip should all be whitespace, so shouldn't require deep review

the deprecations in tooltip require a bit more concentration

2023-05-04 13:14 UTC, nikkimk commented
> apologies for adding unrelated changes here, but one thing led to another:
> 
> * the bem-style css props in tooltip were contrary to guidelines, so we need a minor release to fix them
> * that introduced css linting issues which needed to be addressed
> * fixing those opened up the opportunity to apply more consistent formatting across the repo
> 
> the changes outside of tooltip should all be whitespace, so shouldn't require deep review
> 
> the deprecations in tooltip require a bit more concentration

Totally fine by me. I made the changeset changes as requested. So lmk if you think this is good to go.

2023-05-05 06:50 UTC, bennypowers approved these changes

2023-05-05 06:53 UTC, merged

2023-05-30 20:26 UTC, coreyvickery commented
@nikkimk Not sure why this was closed.

### Overview tab
- Wrong copy under `Overview` heading
- `When to use` heading, third bullet, remove the `-`

### Style tab
- `Anatomy` heading, correct styling for numbers: `Red Hat Text, 14px, 1.5 (21) line height, #4D4D4D`
- `Anatomy` heading, left align the numbers to the image container above
- Spacer images in table are still 2x
- Duplicate cross-links

### Guidelines tab
- Duplicate cross-links

### Code tab
- Duplicate cross-links

### Accessibility tab
- Missing